# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'healthcare.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1491, 951))
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 150, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homepage = QtWidgets.QWidget()
        self.homepage.setStyleSheet("background-color: rgb(0, 253, 255);")
        self.homepage.setObjectName("homepage")
        self.health_care = QtWidgets.QLabel(self.homepage)
        self.health_care.setGeometry(QtCore.QRect(470, 50, 471, 81))
        self.health_care.setStyleSheet("font: 48pt \"Cochin\";\n"
"color: rgb(148, 23, 81);\n"
"")
        self.health_care.setAlignment(QtCore.Qt.AlignCenter)
        self.health_care.setObjectName("health_care")
        self.name = QtWidgets.QLabel(self.homepage)
        self.name.setGeometry(QtCore.QRect(450, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setStyleSheet("font: 24pt \".AppleSystemUIFont\";\n"
"font: italic 24pt \"Arial\";")
        self.name.setObjectName("name")

        self.name_input = QtWidgets.QLineEdit(self.homepage)
        self.name_input.setGeometry(QtCore.QRect(540, 280, 401, 41))
        self.name_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_input.setObjectName("name_input")

        self.surname = QtWidgets.QLabel(self.homepage)
        self.surname.setGeometry(QtCore.QRect(400, 370, 161, 31))
        self.surname.setStyleSheet("\n"
"font: italic 24pt \"Arial\";")
        self.surname.setObjectName("surname")

        self.surname_input = QtWidgets.QLineEdit(self.homepage)
        self.surname_input.setGeometry(QtCore.QRect(540, 360, 401, 41))
        self.surname_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.surname_input.setObjectName("surname_input")

        self.TC = QtWidgets.QLabel(self.homepage)
        self.TC.setGeometry(QtCore.QRect(470, 450, 61, 31))
        self.TC.setStyleSheet("\n"
"font: italic 24pt \"Arial\";")
        self.TC.setObjectName("TC")

        self.TC_input = QtWidgets.QLineEdit(self.homepage)
        self.TC_input.setGeometry(QtCore.QRect(540, 440, 401, 41))
        self.TC_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TC_input.setObjectName("TC_input")

        self.age = QtWidgets.QLabel(self.homepage)
        self.age.setGeometry(QtCore.QRect(450, 540, 71, 31))
        self.age.setStyleSheet("\n"
"font: italic 24pt \"Arial\";")
        self.age.setObjectName("age")

        self.age_input = QtWidgets.QLineEdit(self.homepage)
        self.age_input.setGeometry(QtCore.QRect(540, 530, 401, 41))
        self.age_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.age_input.setObjectName("age_input")

        self.push_button = QtWidgets.QPushButton(self.homepage)
        self.push_button.setGeometry(QtCore.QRect(810, 630, 131, 31))
        self.push_button.setStyleSheet("background-color: rgb(0, 249, 0);\n"
"font: 57 24pt \"Avenir\";")
        self.push_button.setObjectName("push_button")

        self.stackedWidget.addWidget(self.homepage)
        self.symptoms = QtWidgets.QWidget()
        self.symptoms.setObjectName("symptoms")
        self.checkBox = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.checkBox.setStyleSheet("font: 24pt \"Avenir\";\n"
"background-color: rgb(235, 235, 235);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_2.setGeometry(QtCore.QRect(210, 70, 211, 31))
        self.checkBox_2.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_3.setGeometry(QtCore.QRect(450, 70, 131, 31))
        self.checkBox_3.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_4.setGeometry(QtCore.QRect(610, 70, 141, 31))
        self.checkBox_4.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_5.setGeometry(QtCore.QRect(780, 70, 150, 31))
        self.checkBox_5.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_6.setGeometry(QtCore.QRect(960, 70, 161, 31))
        self.checkBox_6.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_7.setGeometry(QtCore.QRect(1150, 70, 91, 31))
        self.checkBox_7.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_8.setGeometry(QtCore.QRect(1270, 70, 131, 31))
        self.checkBox_8.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_9.setGeometry(QtCore.QRect(30, 230, 281, 30))
        self.checkBox_9.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_10.setGeometry(QtCore.QRect(340, 230, 71, 31))
        self.checkBox_10.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_11.setGeometry(QtCore.QRect(440, 230, 170, 30))
        self.checkBox_11.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_12.setGeometry(QtCore.QRect(640, 230, 150, 30))
        self.checkBox_12.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_13.setGeometry(QtCore.QRect(820, 230, 190, 30))
        self.checkBox_13.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_14.setGeometry(QtCore.QRect(1040, 230, 300, 30))
        self.checkBox_14.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_15.setGeometry(QtCore.QRect(30, 380, 170, 30))
        self.checkBox_15.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_16.setGeometry(QtCore.QRect(230, 380, 100, 30))
        self.checkBox_16.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_17.setGeometry(QtCore.QRect(360, 380, 120, 30))
        self.checkBox_17.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_18.setGeometry(QtCore.QRect(510, 380, 150, 30))
        self.checkBox_18.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_19.setGeometry(QtCore.QRect(690, 380, 180, 30))
        self.checkBox_19.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_20.setGeometry(QtCore.QRect(900, 380, 150, 30))
        self.checkBox_20.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_21.setGeometry(QtCore.QRect(1080, 380, 90, 30))
        self.checkBox_21.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_22.setGeometry(QtCore.QRect(1200, 380, 170, 30))
        self.checkBox_22.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_23.setGeometry(QtCore.QRect(430, 510, 140, 30))
        self.checkBox_23.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_24.setGeometry(QtCore.QRect(610, 510, 190, 30))
        self.checkBox_24.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.symptoms)
        self.checkBox_25.setGeometry(QtCore.QRect(850, 510, 130, 30))
        self.checkBox_25.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"font: 24pt \"Avenir\";")
        self.checkBox_25.setObjectName("checkBox_25")
        self.pushButton = QtWidgets.QPushButton(self.symptoms)
        self.pushButton.setGeometry(QtCore.QRect(660, 700, 130, 26))
        self.pushButton.setStyleSheet("background-color: rgb(0, 249, 0);\n"
"font: 24pt \"Avenir\";")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.symptoms)
        self.suggestions = QtWidgets.QWidget()
        self.suggestions.setObjectName("suggestions")
        self.stackedWidget.addWidget(self.suggestions)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.health_care.setText(_translate("MainWindow", "HEALTH CARE"))
        self.name.setText(_translate("MainWindow", "NAME"))
        self.surname.setText(_translate("MainWindow", "SURNAME"))
        self.TC.setText(_translate("MainWindow", "TC"))
        self.age.setText(_translate("MainWindow", "AGE"))
        self.push_button.setText(_translate("MainWindow", "SUBMIT"))
        self.checkBox.setText(_translate("MainWindow", "HEADACHE"))
        self.checkBox_2.setText(_translate("MainWindow", "STOMACH ACHE"))
        self.checkBox_3.setText(_translate("MainWindow", "NAUSESA"))
        self.checkBox_4.setText(_translate("MainWindow", "DIZZINESS"))
        self.checkBox_5.setText(_translate("MainWindow", "JOINT PAIN"))
        self.checkBox_6.setText(_translate("MainWindow", "EYE REDNESS"))
        self.checkBox_7.setText(_translate("MainWindow", "BURN"))
        self.checkBox_8.setText(_translate("MainWindow", "EARACHE"))
        self.checkBox_9.setText(_translate("MainWindow", "BLURRY ON THE BODY"))
        self.checkBox_10.setText(_translate("MainWindow", "CUT"))
        self.checkBox_11.setText(_translate("MainWindow", "TOOTH PAIN"))
        self.checkBox_12.setText(_translate("MainWindow", "HAIR LOSS"))
        self.checkBox_13.setText(_translate("MainWindow", "SKIN REDNESS"))
        self.checkBox_14.setText(_translate("MainWindow", "SHORTNESS OF BREATH"))
        self.checkBox_15.setText(_translate("MainWindow", "NOSE FLOW"))
        self.checkBox_16.setText(_translate("MainWindow", "FEVER"))
        self.checkBox_17.setText(_translate("MainWindow", "COUGH"))
        self.checkBox_18.setText(_translate("MainWindow", "VOMITING"))
        self.checkBox_19.setText(_translate("MainWindow", "SORETHROAT"))
        self.checkBox_20.setText(_translate("MainWindow", "INSOMNIA"))
        self.checkBox_21.setText(_translate("MainWindow", "ACNE"))
        self.checkBox_22.setText(_translate("MainWindow", "NOSE BLEED"))
        self.checkBox_23.setText(_translate("MainWindow", "DIARRHEA"))
        self.checkBox_24.setText(_translate("MainWindow", "COSTIVENESS"))
        self.checkBox_25.setText(_translate("MainWindow", "PHLEGM"))
        self.pushButton.setText(_translate("MainWindow", "SUGGEST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
